### PR TITLE
undetected chromedriver

### PR DESCRIPTION
**Pull request by zutto**
Hi,

As with the new auth challenges, I started looking into alternatives.
I think this could be an option.

- Uses [github.com/ultrafunkamsterdam/undetected-chromedriver](https://github.com/ultrafunkamsterdam/undetected-chromedriver/tree/master) and selenium.
- Real Chrome (114 or higher) as a backend.
- Very simple to update in future when openai changes their site. (the whole login process is like 30 lines of selenium calls)
- Doesn't reuse users actual Chrome session, if anyone happens to actually use Chrome.

There may be problems if/when cloudflare starts presenting proper captcha challenges, but we'll see how this goes.
This still requires some sanity checking and proper error management (and documentation), but otherwise works out of the box (tested only on linux and mac).

----

Thoughts? Anyone up for testing this? 
Ready to be used by running these commands and installing Chrome. (change the python version to whatever you prefer, tested with 3.11)
```
git clone https://github.com/acheong08/OpenAIAuth
cd OpenAIAuth
git fetch origin pull/47/head:selenium
git checkout selenium
python3.11 -m pip install -e .
```

And to rollback to the official one from pypi (or `git checkout main` & `python3.11 -m pip install -e .`)
```
python3.11 -m pip install --upgrade --force-reinstall openaiauth
```

_(note: no MFA or proxy support as of now)_

### CODE REVIEW

**Comment by acheong08** [comment]
This much is unnecessary. I can rollback some code as this has been reverse engineered before and was the default before the mobile method

**Comment by acheong08** [comment]
e.g. https://github.com/acheong08/OpenAIAuth/blob/0.4.0/auth/OpenAiAuth.go

Since no streaming is required, there is tls_client for python. Can be ported over later

**Comment by acheong08** [comment]
Finished updating the Go version: https://github.com/acheong08/OpenAIAuth/commit/bc177ac1a6d78cde32bcd1dd58d6028570d77414

Method for Python is near identical. todo tonight or tomorrow

**Comment by zutto** [comment]
Alright, sounds good. I'll close this PR.

**Pull request closed without merging**
